#!/bin/bash
# make a backup of target file with date appended to it

if [ "$1" == "-help" ]; then
    echo "this program creates a backup of the target file."
    echo "the backup has the current date appended to it."
    echo
    echo "-install          add the program to /usr/bin so you can call it from anywhere."
    echo "'file'            backup 'file'; if a backup already exists, overwrite it (no spam)"
    echo "-b 'file'         backup 'file; if a backup already exists, backup the backup (Yo Dawg!)"
    echo "-restore 'file'   overwrite 'file' with today's backup; delete the backup"
    echo "-rm 'file'        delete today's backups for 'file'"
    echo "-help             show these instructions"

elif [ "$1" == "-install" ]; then
    if [ "$EUID" -ne 0 ]; then
       echo "Please run install as root"
       exit 0
    fi   
    
    echo "installing..."
    cp --backup=t $0 /usr/bin/$(basename $0)
    echo "installed!"

elif [ "$1" == "-b" ]; then
    cp -r --backup=t $2 $2.$(date +"%F")

elif [ "$1" == "-restore" ]; then
    cp -r $2.$(date +"%F") $2

elif [ "$1" == "-rm" ]; then
    rm -r $2.$(date +"%F")*

else
    cp -r --backup $1 $1.$(date +"%F")

fi
