#!/bin/bash

blinkDELAY=1s
blinkSPEED=0.1s
if [ -n "$1" ]; then
    blinkDELAY=$1
    if [ -n "$2" ]; then
        blinkSPEED=$2
    fi
fi

function open {
printf "                                ...',;;:cccccccc:;,..
                             ..,;:cccc::::ccccclloooolc;'.
                          .',;:::;;;;:loodxk0kkxxkxxdocccc;;'..
                        .,;;;,,;:coxldKNWWWMMMMWNNWWNNKkdolcccc:,.
                     .',;;,',;lxo:...dXWMMMMMMMMNkloOXNNNX0koc:coo;.
                  ..,;:;,,,:ldl'   .kWMMMWXXNWMMMMXd..':d0XWWN0d:;lkd,
                ..,;;,,'':loc.     lKMMMNl. .c0KNWNK:  ..';lx00X0l,cxo,.
              ..''....'cooc.       c0NMMX;   .l0XWN0;       ,ddx00occl:.
            ..'..  .':odc.         .x0KKKkolcld000xc.       .cxxxkkdl:,..
          ..''..   ;dxolc;'         .lxx000kkxx00kc.      .;looolllol:'..
        ..'..    .':lloolc:,..       'lxkkkkk0kd,   ..':clc:::;,,;:;,'..
        ......   ....',;;;:ccc::;;,''',:loddol:,,;:clllolc:;;,'........
            .     ....'''',,,;;:cccccclllloooollllccc:c:::;,'..
                    .......'',,,,,,,,;;::::ccccc::::;;;,,''...
                      ...............''',,,;;;,,''''''......
                           ............................\n"
}
################################################################################
function closing {
printf "                             ...'',;;;;::;;;,'..
                            ..,;:cloodddxxxkkkkkkkkxol;..
                         .';codxxkkk000000000000kkkkkkxdoc,..
                       .,codxk0000000000000000000000000kkxddoc,..
                    .':ldxk00000000000000000000000000000000kkxxol:'
                 .,:ldxkk000000000K000000000000000K0000000000kkxkkx:.
              ..,coxkk000000000000000kk000000000000000000000000kxxxxl'
             .,;codxxkk00000000kkk0KK0XNWWWWWWWWWNX0kkkkk00000kkxdool;.
           .';::ccldk00KKKK00oc;..,x00KNNXXXXXNNX0000000000kkkkkkxoc:,..
         ..,;,'..,o00000kkxo,       ,lkKKKKKK0K0d,.;ldk000KK0kxxxdoc:'..
        ..,,'.  .,lk0xxxdol:,..       .,ldddl:,.   .,codkk00kxdollc:,...
        ..'.......',;:c::cclccc::;,,,',,;::::;,;;:clodddxdol:;::;'......
           .....  ...''',,,;;;:ccllloooooooooooooolllcccc:;;,....
                    .......'',,,,,,;;;:::ccclllccc:::;;;,''...
                      ..............'''',,;;;;;,,,''''......
                           .............................\n"
}
################################################################################
function closed {
printf "                                 ...'',;;;;;;;,,...
                            ..,:loxkk000000KKKKKK00xdc,..
                         .,cox000KXXXXXXXXXXXXXXXXXXXK00xo:,..
                      ..;lx000KKKKK000000000000000KKKKXXXXK00xl;..
                   ..,:oxk00000000000000000000000000000000KKKKKK0d:.
                ..;codxkk000kkkkkkkxxxxxxxxxxxxxxxxkkkkkk000000KK0kl'
              ..;ldxkkkkkkxxxxxddddddddddddddddddddddddxxxxxxkkk000xc.
            ..,:oxxkkkkkxxxxdddddddddddddddddddddddddddddddddxxkkkkxl;.
          ..,;codxxkkkxxddddddddddddddddddddddddddddddddxdxxxk000kxdo:..
         .';::::cldk000kkkxxxxxxdddddddddddddddddddddxxxxxkk0000xkddl;..
        .';:;,..,ckXXXKKK0KK000kxk0doddxxdddddddxxxxxxkk0000kkkkkxdoc,..
        .',,''..,:oxxxxxxxkkxkkxk00xxk000000000000KKKKKKK000kxdllll:,..
         .........',,,:ccllllooooxkxxx000kk0000000000000000kxdoc,'...
                 ......',;;::cc::clllloddoox0xdxxkxxxxddollllc:'.
                      .....'',,,,,,,;;;;;::cllc::ccc::;;,,,'...
                          ..................'''..'''......\n"
}

printf "\033[;H" # move cursor to top of the screen
#clear
printf "\e[2m" # dim the text
printf "\e[?25l" # hide the cursor

open
sleep $blinkDELAY 

printf "\033[;H" # top of the screen
#clear
closing
sleep $blinkSPEED

printf "\033[;H" # top of the screen
#clear
closed
sleep $blinkSPEED

printf "\033[;H" # top of the screen
#clear
closing
sleep $blinkSPEED

printf "\033[;H" # top of the screen
#clear
open

printf "\e[?25h" # unhide the cursor
printf "\e[0m" # undim the text
